import test from 'node:test';
import assert from 'node:assert/strict';
import {catalog,rules} from '../src/services/catalog.js';
import {evaluate,selectBenefits,nextAction} from '../src/domain/eligibility.js';
import {validateProfile} from '../src/domain/questions.js';
const p={stage:'pregnant',firstChild:'yes',children:'1',employment:'employed',income:'low',citizenship:'yes',registration:'permanent',received:[]};
const get=(id,patch={})=>evaluate(catalog.find(b=>b.id===id),{...p,...patch},rules);
test('all 18 records have matching rules and source metadata',()=>{assert.equal(catalog.length,18);assert.equal(new Set(catalog.map(b=>b.id)).size,18);for(const b of catalog){assert(rules[b.id]);assert(b.testData);assert(b.updatedAt);assert(b.source.startsWith('https://'));assert(b.documents.length);}});
test('pregnancy employed happy path has concrete next action',()=>{assert.equal(get('b01').match,'eligible');assert.equal(nextAction(selectBenefits(catalog,p,rules)).id,'b01');assert.equal(get('b02').match,'ineligible');});
test('unknown income gives clarification, not rejection',()=>{assert.equal(get('b04',{income:'unknown'}).match,'clarify');assert.equal(get('b15',{stage:'under18',income:'unknown'}).match,'clarify');});
test('temporary registration requires clarification',()=>{assert.equal(get('b15',{stage:'under18',registration:'temporary'}).match,'clarify');assert.equal(get('b15',{stage:'under18',registration:'none'}).match,'ineligible');});
test('high income cannot prove above 2 PM',()=>{assert.equal(get('b06',{stage:'under18',income:'high'}).match,'clarify');});
test('received items stay visible even after stage changes',()=>{assert.equal(get('b02',{received:['birth']}).match,'received');});
test('multiple children allowed with first biological child',()=>{assert.doesNotThrow(()=>validateProfile({...p,firstChild:'yes',children:'3'}));});
test('large-family and duplicate rows excluded from automatic recommendations',()=>{for(const id of ['b10','b11','b12','b13','b14','b17','b18'])assert.equal(get(id,{children:'3'}).match,'excluded');});
test('non-citizen employed maternity retained, capital excluded',()=>{assert.equal(get('b01',{citizenship:'no'}).match,'eligible');assert.equal(get('b05',{stage:'under18',citizenship:'no'}).match,'ineligible');});
test('deadline ambiguity does not imply entitlement',()=>{assert.equal(get('b02',{stage:'under18'}).match,'clarify');});
test('profile validation rejects unknown fields and invalid categories',()=>{assert.throws(()=>validateProfile({...p,income:10000}));assert.throws(()=>validateProfile({...p,name:'Real name'}));assert.throws(()=>validateProfile({...p,received:['capital','capital']}));});
test('incomplete answers never become confirmed eligible',()=>{for(const b of selectBenefits(catalog,{},rules))assert.notEqual(b.match,'eligible');});
